#!/bin/bash -f

SED=`which sed`

[ $# == 0 ] && echo $USAGE && exit 1
while getopts "p:b:c:" OPTION
do
    case $OPTION in
        p) PATH=$OPTARG;;
        b) BRANCH=$OPTARG;;
        c) COMMIT=$OPTARG;;
    esac
done

[ -z $PATH ] && exit 1

# Remove heading and trailing spaces in branch and commit
echo -n "branch " > $PATH
echo "$BRANCH" | $SED -e 's/^ *//' -e 's/ *$//' >> $PATH
echo -n "commit " >> $PATH
echo "$COMMIT" | $SED -e 's/^ *//' -e 's/ *$//' >> $PATH
